spring:
  config:
    activate:
      on-profile: local
  application:
    name: Arquetipo de Spring Boot
  cassandra:
    contact-points: localhost
    keyspace-name: ticket_digital
    port: 9042
    username: admin
    password: admin
    local-datacenter: datacenter1
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ticket-grupo
      auto-offset-reset: earliest
    producer:
      client-id: ticket-producer
  redis:
    host: localhost
    port: 6379
    password: passwordDev
ticket:
  kafka:
    topic: ticket-topic
    trusted-packages: com.axity.ticket.commons.dto